In [2]:
import numpy as np

# Write a function so that the columns of the output matrix are powers of the inputvector

In [14]:
def vander_matrix(x_array, inc_bool):
    N = len(x_array)
    if inc_bool:
        vand_matrix = np.column_stack([x**(i) for i in range(N)])
    else:
        vand_matrix = np.column_stack([x**(N - i -1) for i in range(N)])
    return vand_matrix

In [15]:
x = np.array([1, 2, 3, 5])
print(vander_matrix(x, True))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [16]:
x = np.array([1, 2, 3, 5])
print(vander_matrix(x, False))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [20]:
x = np.array([1, 2, 3, 4, 5])
np.vander(x)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [21]:
np.vander(x, increasing = True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

# Question:Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [95]:
def moving_average(a, n):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [93]:
y = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [96]:
moving_average(y, 4)

array([25., 35., 45., 55., 65., 75., 85.])

In [97]:
moving_average( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])